brew 'autojump'
brew 'bat'
brew 'eza'
brew 'thefuck'
brew 'fzf', postinstall: 'mkdir -p ~/.fzf-git && curl -fsSLo ~/.fzf-git/fzf-git.sh https://raw.githubusercontent.com/junegunn/fzf-git.sh/refs/heads/main/fzf-git.sh'
brew 'git'
brew 'luarocks'
brew 'neovim'
brew 'powerlevel10k'
brew 'rg'
brew 'stow'
brew 'zoxide'
brew 'zsh', postinstall: 'bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'kitty'
