# THEME 
include 'Alabaster.conf'

# FONTS
font_family FiraCode Nerd Font Mono
font_size 12.0
# feels not so bright with that
text_composition_strategy legacy
disable_ligatures always

# CURSOR
cursor_shape underline
cursor_shape_unfocused beam
cursor_underline_thickness 2.5
# shell_intergration no-cursor
cursor_blink_interval 0
cursor_trail 10
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 0

# TERMINAL_BELL
enable_audio_bell no

# WINDOW_LAYOUT
# new -> left, rest -> right
enabled_layouts Tall, *
window_border_width 0pt
window_margin_width 8
inactive_text_alpha 0.75

# TAB_BAR
# tab_bar_margin_height 4 0
# tab_bar_style separator
# tab_bar_align left
# tab_bar_min_tabs 1
# tab_separator  ""
# tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._a6adc8}{fmt.bg.default} {title.split()[0]} {fmt.fg._5c6370}{fmt.bg.default} "
# active_tab_title_template "{fmt.fg._585b70}{fmt.bg.default}{fmt.fg._bac2de}{fmt.bg.default} {title.split()[0]} {fmt.fg._585b70}{fmt.bg.default} "
tab_bar_style hidden

# COLOR_SCHEME
background_opacity 0.9
background_blur 45
dynamic_background_opacity yes

# ADVANCED
#  TODO:
# - why does *_as_alt not work?
#
editor /opt/homebrew/bin/nvim
macos_option_as_alt yes

# SCROLLING
#  NOTE:
# - use cmd+shift+[ and _+[ for prev/next tab
# - use ctrl+shift+[ and _+[ for prev/next window
#
map ctrl+k scroll_line_up
map ctrl+j scroll_line_down
map ctrl+u scroll_page_up
map ctrl+d scroll_page_down
map cmd+enter launch --cwd=current
map cmd+shift+enter new_window
map cmd+s select_tab


# BEGIN_KITTY_THEME
# Sea Shells
include current-theme.conf
# END_KITTY_THEME
